# Generated by Django 4.0.4 on 2022-06-02 17:58

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('league_name', models.CharField(max_length=50)),
                ('points_for_win', models.IntegerField(default=3)),
                ('points_for_lost', models.IntegerField(default=0)),
                ('points_for_draw', models.IntegerField(default=1)),
                ('max_number_of_teams_in_league', models.IntegerField(default=10)),
                ('max_number_of_players_in_team', models.IntegerField(default=2)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=10)),
                ('team_league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.league')),
            ],
        ),
        migrations.CreateModel(
            name='TeamPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_nick', models.CharField(max_length=20)),
                ('team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='manager.team')),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_is_ended', models.BooleanField(default=False)),
                ('match_date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('match_duration', models.DurationField(default='01:30:00')),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.league')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.team')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('Match has been won', 'Match Won'), ('Match has been lost', 'Match Lost'), ('Match has been drawn', 'Match Draw'), ('Goal has been scored', 'Match Goal'), ('Event not specified', 'Missing')], default='Event not specified', max_length=20)),
                ('event_time', models.TimeField(blank=True, default=django.utils.timezone.now)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.match')),
                ('player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='manager.teamplayer')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.team')),
            ],
        ),
    ]
