# Generated by Django 4.0.4 on 2022-05-12 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_eventtype_result_sumofpoints_team_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='league',
            name='max_number_of_teams',
            field=models.IntegerField(),
        ),
    ]
